Support custom MTU on VPCs
terraform-google-modules/terraform-google-network pull request #221
Opened 2020-12-09 18:14 UTC by memes

This is a potential update to address feature request #220. It adds an `mtu` variable to root and vpc modules that will set MTU on `google_compute_network` resource.

The update has been tested in a few non-production VPCs without any problems yet.

*Note:* MTU suport has a dependency on release [3.45.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.45.0) of google provider.

2020-12-09 21:19 UTC, morgante requested changes
You'll also need to update the version in `examples/`.

2020-12-10 04:28 UTC, memes commented
I've changed the examples so that they pass with `make docker_test_integration` executed locally. Full tests failed until I made the change in 8063a17 too.

2020-12-10 05:30 UTC, morgante approved these changes
Thanks for the contribution. Test failures look unrelated.

2020-12-10 05:30 UTC, merged

2020-12-29 16:43 UTC, jmymy commented
Is this a breaking change? It's a destructive action to change the MTU on existing VPCs

`  # module.vpc.google_compute_network.network must be replaced
+/- resource "google_compute_network" "network" {
        auto_create_subnetworks         = false
        delete_default_routes_on_create = false
      + gateway_ipv4                    = (known after apply)
      ~ id                              = "XXXXX" -> (known after apply)
      ~ mtu                             = 0 -> 1460 # forces replacement
        name                            = "XXXXX"
        project                         = "XXXXXX"
        routing_mode                    = "GLOBAL"
      ~ self_link                       = "XXXXXX" -> (known after apply)
    }`

2020-12-29 16:53 UTC, jmymy commented
https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_network.go#L78

2020-12-29 18:12 UTC, memes commented
Tested and confirmed that is is a breaking change for those upgrading from v2.x to v3.0.0. Personally I think this is acceptable given the module's major version has changed for this and other changes, but I'm open to other points of view.

FYI - By adding an explicit `mtu = 0` input to the module I avoided recreating a test network on upgrade from v2.6.0 to v3.0.0. @jmymy can you confirm that works in your environment too?

Options:
1. Leave default MTU variable at `1460` to match intent, and document the workaround
2. Set default input value for `mtu` to `0` or `null`; this will prevent breakage for those upgrading from v2.x.x to v3.0.x but will bring in the same problem for v3.0.0 users who do not explicitly set an MTU value when the next release is published.

@morgante @bharathkkb - how do you want to proceed?

2020-12-29 18:58 UTC, bharathkkb commented
A quick look at the API seems to imply that it is possible to update MTU. If that is the case this should not be marked as `ForceNew` in the provider. I will open an issue on the provider to confirm, but short term setting it to `null` could be a workaround.

2020-12-29 19:57 UTC, morgante commented
Indeed, you can override the MTU as a workaround. Since this is a (breaking) major version change, I don't think we need to change the module behavior.