chore: adding instance creation to network service tiers docs
terraform-google-modules/terraform-google-network pull request #303
Opened 2021-06-10 02:18 UTC by mark1000

Destined for
https://cloud.google.com/network-tiers/docs/using-network-service-tiers#creating_vm_instances

2021-06-10 03:24 UTC, morgante commented
@mark1000 Looks like this has merge conflicts, can you PTAL?

2021-06-10 19:27 UTC, mark1000 commented
I think I fixed the merge issue. PTAL? Thanks!

2021-06-14 22:15 UTC, mark1000 commented
@morgante Do you know why the int-trigger failed? Is there a way to retry it?

2021-06-14 22:58 UTC, morgante requested changes
Test failure is unrelated.

2021-06-14 22:58 UTC, morgante commented on examples/network_service_tiers/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
This file should not be committed.

2021-06-14 23:27 UTC, mark1000 commented
Deleted. Thanks.

On Mon, Jun 14, 2021 at 3:58 PM Morgante Pell ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Test failure is unrelated.
> ------------------------------
>
> In examples/network_service_tiers/.terraform.lock.hcl
> <https://github.com/terraform-google-modules/terraform-google-network/pull/303#discussion_r651331287>
> :
>
> > @@ -0,0 +1,40 @@
> +# This file is maintained automatically by "terraform init".
>
> This file should not be committed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/terraform-google-modules/terraform-google-network/pull/303#pullrequestreview-683420901>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AASB6AJHM2WNJI3VPJQT6OLTS2CSPANCNFSM46NFCA4A>
> .
>

2021-06-14 23:47 UTC, morgante approved these changes

2021-06-14 23:48 UTC, merged