fix: "subnets" input order differs from "subnets_self_links" output order
terraform-google-modules/terraform-google-network pull request #401
Opened 2022-11-12 22:05 UTC by tuunit

Refers to: https://github.com/terraform-google-modules/terraform-google-network/issues/400

TL;DR
Unfortunately, adding subnets is handled via a list input but the output is generated from a map inside the subnets module. Which is lexicographically ordered. Therefore using the same index for the subnets input list and the subnets_self_links list doesn't necessarily reflect the same subnets.

2022-11-27 11:23 UTC, tuunit commented
@apeabody, @bharathkkb
Are you able to tell me what failed during the Cloud Build? I executed the full test suite against my own cloud project and everything was succesful. Therefore I don't know how to continue.

2022-11-28 17:00 UTC, apeabody commented
Hi @tuunit - Thanks for the contribution!

I haven't looked at it carefully, but here is some relevant test output:
```
    apply.go:34: 
        	Error Trace:	/workspace/test/integration/submodule_vpc_serverless_connector/apply.go:34
        	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:289
        	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:299
        	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:322
        	            				/workspace/test/integration/submodule_vpc_serverless_connector/stages.go:31
        	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:322
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: Invalid index
        	            	│ 
        	            	│   on main.tf line 47, in module "serverless-connector":
        	            	│   47:     subnet_name = module.test-vpc-module.subnets["us-central1/serverless-subnet"].name
        	            	│     ├────────────────
        	            	│     │ module.test-vpc-module.subnets is tuple with 1 element
        	            	│ 
        	            	│ The given key does not identify an element in this collection value: a
        	            	│ number is required.
        	            	╵}
        	Test:       	TestSubmoduleServerlessConnector
```

2022-11-29 01:54 UTC, bharathkkb requested changes
Thanks for the PR @tuunit. We want to continue using for_each as we would not want resource recreation to happen incase element index changes due to add/remove which is a drawback with count. 

For https://github.com/terraform-google-modules/terraform-google-network/issues/400, could an alternate approach be to add a new output in the subnets modules which uses the input list to reorder the output self links?

2022-12-04 10:14 UTC, tuunit commented
> Hi @tuunit - Thanks for the contribution!
> 
> I haven't looked at it carefully, but here is some relevant test output:
> 
> ```
>     apply.go:34: 
>         	Error Trace:	/workspace/test/integration/submodule_vpc_serverless_connector/apply.go:34
>         	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:289
>         	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:299
>         	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:322
>         	            				/workspace/test/integration/submodule_vpc_serverless_connector/stages.go:31
>         	            				/workspace/test/integration/submodule_vpc_serverless_connector/terraform.go:322
>         	Error:      	Received unexpected error:
>         	            	FatalError{Underlying: error while running command: exit status 1; ╷
>         	            	│ Error: Invalid index
>         	            	│ 
>         	            	│   on main.tf line 47, in module "serverless-connector":
>         	            	│   47:     subnet_name = module.test-vpc-module.subnets["us-central1/serverless-subnet"].name
>         	            	│     ├────────────────
>         	            	│     │ module.test-vpc-module.subnets is tuple with 1 element
>         	            	│ 
>         	            	│ The given key does not identify an element in this collection value: a
>         	            	│ number is required.
>         	            	╵}
>         	Test:       	TestSubmoduleServerlessConnector
> ```

I had a look at the mentioned error but it actually occurs even without my changes on the current master branch.

2022-12-04 10:23 UTC, tuunit commented
> Thanks for the PR @tuunit. We want to continue using for_each as we would not want resource recreation to happen incase element index changes due to add/remove which is a drawback with count.
> 
> For #400, could an alternate approach be to add a new output in the subnets modules which uses the input list to reorder the output self links?

Just to clarify which option you would prefer?
1. add a new output list which has the same order as the input list
2. add a new bool "flag" to determine if the self_links output should be ordered as is (lexicographically or like the input list) (if this is your preferred choice which of the two orders should be the default?)

2022-12-12 07:55 UTC, tuunit commented
> > Thanks for the PR @tuunit. We want to continue using for_each as we would not want resource recreation to happen incase element index changes due to add/remove which is a drawback with count.
> > For #400, could an alternate approach be to add a new output in the subnets modules which uses the input list to reorder the output self links?
> 
> @bharathkkb Just to clarify which option you would prefer?
> 
> 1. add a new output list which has the same order as the input list
> 2. add a new bool "flag" to determine if the self_links output should be ordered as is (lexicographically or like the input list) (if this is your preferred choice which of the two orders should be the default?)

@bharathkkb @apeabody just a reminder about my question :)

2022-12-12 16:49 UTC, apeabody commented
Thanks for the contribution @tuunit!  I'll need to defer to @bharathkkb on the question, however I merged the recent repo changes and re-trigger the tests so we can get a current INT CI.

2022-12-16 02:52 UTC, bharathkkb commented
@tuunit sorry for the delay. I think option 1 would be better adding just the sorted output.

2023-02-25 23:09 UTC, closed without merging